### ISSUE TITLE
Can't connect to Ledger Live

### ISSUE THREAD

**Issue by Marcok-99** [api3dao/api3-market-issues#2]
**Describe the bug**
I want to connect the wallet when a dApi is selected on polygon. Polygon is supported on Ledger Live (over Wallet Connect).
I get the following message in Ledger Live: 

<img width="1215" alt="Bildschirmfoto 2023-07-24 um 18 25 23" src="https://github.com/api3dao/api3-market-issues/assets/39245842/2f6eadd5-f1b8-411d-b9d4-9ea2a4f19e6a">

Same issue when Ethereum Mainnet is selected. 
<img width="1300" alt="Bildschirmfoto 2023-07-24 um 18 32 56" src="https://github.com/api3dao/api3-market-issues/assets/39245842/2fcfd567-f570-412a-ac5a-ca35e061bb46">
**To Reproduce**
1. Go to API3-Market
2. Select Wallet-Connect --> Ledger

**Expected behavior**
Connect to the API3-Market by using Ledger-Live. 

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4.1(c)
 - Browser: safari 

**Additional context**
For me it`s not important. Just wanted to test a few things. 
However, assume that others also have the problem.

**Comment by PrenaamD** [comment]
I was not able to exactly reproduce it. However, here are the steps I went through

1. Click Connect Wallet
2. Select Ledger on the WalletConnect modal
3. Click Open Ledger Live on the popup
4. Ledger Live opens  with an error message regarding unsupported blockchains (See screenshots for details)
5. Select the Polygon account to connect to the API3 Market
6. The Connect button is disabled

![WalletConnect_ledgerLive_Failure](https://github.com/api3dao/api3-market-issues/assets/89918145/7ae48f9d-1d73-40df-babd-14433e9fb24e)

it seems that Ledger Live requires the marked (*) account to be added (Arbiturm in this case). After having added the required Arbitrum account, the Connect button became enabled and the account was able to connect to the API3 Market.

![WalletConnect_ledgerLive_Success](https://github.com/api3dao/api3-market-issues/assets/89918145/dca7c3fd-1e8e-44b6-8de5-538b03e776cf)

Desktop:
OS: Windows 11
Browser: Chrome 115.0.5790.171 (Official Build) (64-bit)
Leger Live 2.64.2

**Comment by Marcok-99** [comment]
It worked after I added the other chains. Thanks!
